server:
  port: 8081

# nacos config
nacos:
  server-address: localhost:8848
  namespace: video
  group: video_data
  user-name: ses
  user-password: Ss@123456

# service instance config
service:
  instance:
    enable: true
    ephemeral: false
    service-name: video_datahub
    weight: 10.0
    cluster-name: HB1
    check-url: health
